# Generated by Django 3.2.5 on 2021-08-21 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('cv_link', models.CharField(max_length=200)),
                ('facebook_link', models.CharField(max_length=200)),
                ('linkdin_link', models.CharField(max_length=200)),
                ('github_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=35)),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.about')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('Client_name', models.CharField(max_length=35)),
                ('company', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('speech', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('video', models.FileField(null=True, upload_to='videos/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=70)),
                ('images', models.ImageField(upload_to='')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.about')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=60)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('thumbnail', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=22)),
                ('message', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('portfolio_projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.portfolio_projects')),
            ],
        ),
        migrations.CreateModel(
            name='Experiernces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('posision', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=70)),
                ('company_logo', models.ImageField(upload_to='')),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.about')),
            ],
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('institution_name', models.CharField(max_length=70)),
                ('institution_logo', models.ImageField(upload_to='')),
                ('education', models.CharField(max_length=20)),
                ('CGPA', models.FloatField()),
                ('Out_of', models.FloatField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.about')),
            ],
        ),
    ]
